services:
  - type: web
    name: backend-tool-research-keywords
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      apt-get update
      apt-get install -y google-chrome-stable
      npm install
    startCommand: 'node server.js'
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: '/usr/bin/google-chrome-stable'
